
version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
